version: '3.8'

services:
  tempconverter-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: passsword
      MYSQL_DATABASE: tempconverter_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - tempconverter-db-data:/var/lib/mysql
    networks:
      - tempconverter-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  tempconverter-web:
    image: docker.io/vherve/tempconverter:latest
    ports: 
      - "80:5000"
    environment:
      DB_USER: db_user
      DB_PASS: db_password
      DB_HOST: tempconverter-db
      DB_NAME: tempconverter_db
      STUDENT: "Valentin Hervé"
      COLLEGE: Algebra
    depends_on:
      - tempconverter-db
    networks:
      - tempconverter-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  tempconverter-network:
    driver: overlay

volumes:
  tempconverter-db-data:

