apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter
  template:
    metadata:
      labels:
        app: tempconverter
    spec:
      containers:
      - name: web
        image: docker.io/vherve/tempconverter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: db_user
        - name: DB_PASS
          value: db_password
        - name: DB_HOST
          value: tempconverter-db
        - name: DB_NAME
          value: tempconverter_db
        - name: STUDENT
          value: "Valentin Hervé"
        - name: COLLEGE
          value: "Algebra"
---
apiVersion: v1
kind: Service
metadata:
  name: tempconverter
spec:
  selector:
    app: tempconverter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

